### ISSUE TITLE
Implement Angular 12 support

### ISSUE THREAD

**Issue by dmitry-lomakin** [solarwinds/nova#410]
**Is your feature request related to a problem? Please describe.**

The problem is that I'd like to utilize Nova bits by an Angular 12-based application but I cannot do that because ther's now support for this Angular version.

**Describe the solution you'd like**

Nova should work with Angular 12

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by Blakesalot** [comment]
Hi, @dmitry-lomakin, the work to make Nova compatible with v12 apps was done by @lukasholcik, in July:
https://github.com/solarwinds/nova/pull/385

Hopefully any compatibility issue you've run into this soon after it was done will have a trivial fix.

As an fyi, active development has dramatically slowed on Nova as there's not a dedicated team working on it currently. Feel free to contribute any fix and notify @mzknksh or anyone on the Bravo team to review changes.
